# Generated by Django 5.2.7 on 2025-10-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='end_location',
            new_name='current_location',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='start_location',
            new_name='dropoff_location',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='cycle_type',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='driver_name',
        ),
        migrations.AddField(
            model_name='trip',
            name='current_cycle_used_hours',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_location',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='total_miles',
            field=models.FloatField(default=0),
        ),
    ]
